export const featuredHouses = [
    {
        id: 1,
        title: "Woodlandside",
        price: "$ 20.000.000",
        img: "/woodlandside.png",
        status: "New House",
        sellerName: "Robert Fox",
        pfp: "/robert-fox-pfp.png",
        address: "Dr. San Jose, South Dakota"
    },
    {
        id: 2,
        title: "The Old Lighthouse",
        price: "$ 44.000.000",
        img: "/the-old-lighthouse.png",
        status: "Best Deals",
        sellerName: "Ronald Richards",
        pfp: "/robert-fox-pfp.png",
        address: "Santa Ana, Illinois",
    },
    {
        id: 3,
        title: "Cosmo's House",
        price: "$ 22.000.000",
        img: "/cosmos-house.png",
        status: "Popular",
        sellerName: "Jenny Wilson",
        pfp: "/robert-fox-pfp.png",
        address: "Preston Rd. Inglewood, Maine 98380",
    },
    {
        id: 4,
        title: "Cosmo's House",
        price: "$ 22.000.000",
        img: "/cosmos-house.png",
        status: "Popular",
        sellerName: "Jenny Wilson",
        pfp: "/robert-fox-pfp.png",
        address: "Preston Rd. Inglewood, Maine 98380",
    },
    {
        id: 5,
        title: "Cosmo's House",
        price: "$ 22.000.000",
        img: "/cosmos-house.png",
        status: "Popular",
        sellerName: "Jenny Wilson",
        pfp: "/robert-fox-pfp.png",
        address: "Preston Rd. Inglewood, Maine 98380",
    },
    {
        id: 6,
        title: "Cosmo's House",
        price: "$ 22.000.000",
        img: "/cosmos-house.png",
        status: "Popular",
        sellerName: "Jenny Wilson",
        pfp: "/robert-fox-pfp.png",
        address: "Preston Rd. Inglewood, Maine 98380",
    },
    {
        id: 7,
        title: "Cosmo's House",
        price: "$ 22.000.000",
        img: "/cosmos-house.png",
        status: "Popular",
        sellerName: "Jenny Wilson",
        pfp: "/robert-fox-pfp.png",
        address: "Preston Rd. Inglewood, Maine 98380",
    },
    {
        id: 8,
        title: "Cosmo's House",
        price: "$ 22.000.000",
        img: "/cosmos-house.png",
        status: "Popular",
        sellerName: "Jenny Wilson",
        pfp: "/robert-fox-pfp.png",
        address: "Preston Rd. Inglewood, Maine 98380",
    },
    {
        id: 9,
        title: "Cosmo's House",
        price: "$ 22.000.000",
        img: "/cosmos-house.png",
        status: "Popular",
        sellerName: "Jenny Wilson",
        pfp: "/robert-fox-pfp.png",
        address: "Preston Rd. Inglewood, Maine 98380",
    },
    {
        id: 10,
        title: "Cosmo's House",
        price: "$ 22.000.000",
        img: "/cosmos-house.png",
        status: "Popular",
        sellerName: "Jenny Wilson",
        pfp: "/robert-fox-pfp.png",
        address: "Preston Rd. Inglewood, Maine 98380",
    },
]