import Benefits from "@/components/sections/benefits/Benefits";
import Info from "@/components/sections/info/Info";
import Main from "@/components/sections/main/Main";
import Reviews from "@/components/sections/reviews/Reviews";
import Second from "@/components/sections/second/Second";
import Tour from "@/components/sections/tour/Tour";
import Head from "next/head";
import Image from "next/image";

export default function Home() {
    return (
        <>
            <Head>
                <title>HouseHunter</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Main/>
            <Second/>
            <Benefits/>
            <Tour/>
            <Reviews/>
            <Info/>
        </>
    );
}
