import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import First from "@/components/First/First";
import Second from "@/components/Second/Second";
import Benefits from "@/components/Benefits/Benefits";
import Reviews from "@/components/Reviews/Reviews";
import Info from "@/components/Info/Info";
import Tour from "@/components/Tour/Tour";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    return (
        <>
            <Head>
                <title>HouseHunter</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <First />
            <Second />
            <Benefits />
            <Tour />
            <Reviews />
            <Info />
        </>
    );
}
